from typing import Final

TEMPORARY_BAN: Final = "TEMPORARY"
PERMANENT_BAN: Final = "PERMANENT"
IDLE_KICK: Final = "IDLE"
HOST_CLOSED_CONNECTION_KICK: Final = "HOST"
TEAM_KILLING_KICK: Final = "TEAM KILLING"

OFFENSIVE_GAME_MODE = "OFFENSIVE"
WARFARE_GAME_MODE = "WARFARE"
