from typing import Final

TEMPORARY_BAN: Final = "TEMPORARY"
PERMANENT_BAN: Final = "PERMANENT"
IDLE_KICK: Final = "IDLE"
HOST_CLOSED_CONNECTION_KICK: Final = "HOST"
TEAM_KILLING_KICK: Final = "TEAM KILLING"

OFFENSIVE_GAME_MODE: Final = "OFFENSIVE"
WARFARE_GAME_MODE: Final = "WARFARE"

TCP_TIMEOUT_READ: Final = 1
TCP_TIMEOUT: Final = 25
CHUNK_SIZE: Final = None
